### PR TITLE
GitHubTeacher Adds Orlando File

### PR DESCRIPTION
**Pull request by githubteacher**
This PR adds content to the Orlando file 🐭  🎢 

Some open ❓ for this PR:
- if you've never visited Florida -- what kind of things interest you?
- @crichID what kind of things do you like to do with younglings?

### CODE REVIEW

**Comment by crichID** [comment]
@githubteacher my little guy loves Legos and Trains. Any recommendations?

**Comment by CSAmador** [comment]
Gators!

**Comment by githubteacher** [comment]
@CSAmador I added some Gator stuff in 0bd831a

**Comment by githubteacher** [comment]
@crichID does this look ready to 🚢 ?

**Pull request merged**
