### PR TITLE
GitHubTeacher adds LA file

### PR DESCRIPTION
**Pull request by WeitiHuang**
This PR adds content to the LA file :mouse2: 

Some open :question: for this PR:

### CODE REVIEW

**Comment by drepshas** [comment]
looks great

**Comment by mango-pickle** [comment]
LA LA land looks fine :smile:

**Comment by WeitiHuang** [comment]
Add Getty Center

**Comment by WeitiHuang** [comment]
I added Disney concert hall and Universal Studio.

**Pull request merged**
